### Evaluate cell cycle and NF-kB - PDX Tibia
***incomplete--needs to be aligned with lung met
```{r}
pdx_tibia <- qs::qread("output/seurat_objects/pdx_tibia.qs")

pdx_tibia <- kill_cc(pdx_tibia)

p5 <- r_dim_plot(pdx_tibia,
    reduction = "fdl",
    group.by = "Phase",
    label = FALSE) +
  labs(title = "OS-17 Primary Tibia - Cell Cycle") +
  theme(legend.position = "right")
p5

# Pull the transcription-factor regulated gene sets from msigdb
sigs <- msigdbr::msigdbr(species = "Homo sapiens",
    category = "H") %>%
  select(gs_name, gene_symbol)

gs <- "HALLMARK_TNFA_SIGNALING_VIA_NFKB"

cell_ranks <- AUCell::AUCell_run(
  pdx_tibia[["RNA"]]$counts,
  sigs %>% filter(gs_name == gs) %>% pull(gene_symbol)
)
pdx_tibia$nfkb_activity <- AUCell::getAUC(cell_ranks)[1,]

p1 <- FeaturePlot(pdx_tibia,
  "nfkb_activity",
  reduction = "fdl",
  cols = c("#EEEEEE", "#ae0600"),
  min.cutoff = 0.15,
  pt.size = 1,
  order = TRUE) +
  coord_fixed()
p1

```


## Evaluate gene expression
```{r}
```

### Evaluate gene expression - Lung Met

```{r}
# Load the dataset
pdx_lungs <- qs::qread("output/seurat_objects/pdx_lungs.qs")

# Pull the transcription-factor regulated gene sets from msigdb
sigs <- msigdbr::msigdbr(species = "Homo sapiens",
    category = "H") %>%
  select(gs_name, gene_symbol)

degs <- subset(pdx_lungs, idents = c(0, 2, 5, 6)) %>%
  FindAllMarkers()

pathways <- future_lapply(unique(degs$cluster), function(i) {
  clust_degs <- degs %>%
    filter(cluster == i & p_val_adj < 0.05) %>%
    arrange(-avg_log2FC) %>%
    pull(avg_log2FC, name = gene)
  clusterProfiler::GSEA(clust_degs,
    TERM2GENE = sigs,
    nPermSimple = 10000) %>%
    mutate(p.adjust = -log10(p.adjust))
})

FeaturePlot()
plots <- lapply(seq_along(pathways), function(p) {
  enrichplot::dotplot(pathways[[p]] %>% filter(NES > 0),
    x = "NES",
    showCategory = 15,
    title = paste("Cluster", unique(degs$cluster)[p]))
})

patchwork::wrap_plots(plots, ncol = 2)

gs <- "HALLMARK_TNFA_SIGNALING_VIA_NFKB"

cell_ranks <- AUCell::AUCell_run(
  pdx_lungs[["RNA"]]$counts,
  sigs %>% filter(gs_name == gs) %>% pull(gene_symbol)
)
pdx_lungs$nfkb_activity <- AUCell::getAUC(cell_ranks)[1,]

FeaturePlot(pdx_lungs,
  "nfkb_activity",
  reduction = "fdl",
  cols = c("#EEEEEE", "#ae0600"),
  min.cutoff = 0.15,
  pt.size = 1,
  order = TRUE) +
  coord_fixed()

pdx_lungs <- kill_cc(pdx_lungs)

r_dim_plot(pdx_lungs,
    reduction = "fdl",
    group.by = "Phase",
    label = FALSE) +
  labs(title = "OS-17 Lung Mets - Cell Cycle") +
  theme(legend.position = "right")

```







## GSEA
```{r}
degs <- FindAllMarkers(pdx_lungs_cc) %>%
  filter(p_val_adj < 0.05) %>%
  arrange(-avg_log2FC)

pathways <- mclapply(unique(degs$cluster), function(clust) {
  genes <- degs %>%
    filter(cluster == clust)

  p <- clusterProfiler::gseGO(
    geneList = genes,
    OrgDb = org.Hs.eg.db::org.Hs.ed.db,
    ont = "BP",
    keyType = "SYMBOL",
    nPermSimple = 10000,
    eps = 0
  )

  return(p)
}, mc.cores = parallelly::availableCores())
```



## Test cell cycle regression
```{r}
pdx_tibia_cc <- pdx_tibia %>%
  ScaleData(
    vars.to.regress = c("S.Score", "G2M.Score"),
    features = rownames(x = pdx_tibia)) %>%
  RunPCA() %>%
  FindNeighbors(reduction = "pca", k.param = 100L) %>%
  FindClusters(resolution = 0.8) %>%
  RunUMAP(reduction = "pca", dims = 1:30)

r_dim_plot(pdx_tibia_cc, group.by = "Phase")

pdx_tibia_cc <- run_fdl(pdx_tibia_cc)

r_dim_plot(pdx_tibia_cc, group.by = "seurat_clusters", reduction = "fdl")
r_feature_plot(pdx_tibia_cc, "PAX7", reduction = "fdl")
```

## GSEA
```{r}
degs <- FindAllMarkers(pdx_tibia_cc) %>%
  filter(p_val_adj < 0.05) %>%
  arrange(-avg_log2FC)

pathways <- mclapply(unique(degs$cluster), function(clust) {
  genes <- degs %>%
    filter(cluster == clust)

  p <- clusterProfiler::gseGO(
    geneList = genes,
    OrgDb = org.Hs.eg.db::org.Hs.ed.db,
    ont = "BP",
    keyType = "SYMBOL",
    nPermSimple = 10000,
    eps = 0
  )

  return(p)
}, mc.cores = parallelly::availableCores())
```



### Check for co-occurrence of IL6, CXCL8, p21, and Ki67 in human lung mets
```{r}
tmets <- list()
for (i in c("S0058", "S0059")) {
    r_dim_plot(mets[[i]], title = paste(i, "Clusters"))
    r_feature_plot(mets[[i]], "IL6", title = paste(i, "COL1A1 Expression"))
    DimPlot(mets[[i]],
            cells.highlight = WhichCells(mets[[i]], expression = IL6 > 1),
            cols.highlight = "#1F00B8",
            pt.size = 1) +
        labs(title = paste(i, "IL6 Expression >2")) +
        theme(legend.position = "none") +
        coord_fixed()

    # Isolate the tumor cells (list previously generated)
    # tmets[[i]] <- subset(mets[[i]],
    #     cells = readRDS(paste0(i, "TumorCells.rds")))

    # tmets[[i]] <- process_seurat(tmets[[i]])
    tmets[[i]] <- mets[[i]]
    r_dim_plot(tmets[[i]], title = paste(i, "Tumor Subclusters"))
    r_feature_plot(tmets[[i]], "IL6", title = paste(i, "IL6 Expression"))
    r_feature_plot(tmets[[i]], "CXCL8", title = paste(i, "CXCL8 Expression"))
    DimPlot(tmets[[i]],
            cells.highlight = WhichCells(tmets[[i]], expression = IL6 > 1),
            cols.highlight = "#1F00B8",
            pt.size = 1) +
        labs(title = paste(i, "IL6 Expression >1")) +
        theme(legend.position = "none") +
        coord_fixed()
}

tumor_cocx <- SCTransform(tumor_cocx)
s <- c("counts", "data", "scale.data")
p <- lapply(s, function(i) {
    t <- GetAssayData(tumor_cocx, slot = i) %>%
        as.data.frame() %>%
        t() %>%
        as.data.frame()

    return(
        ggplot(t, aes(IL6, CDKN1A)) +
            geom_point()
    )
})
p[[1]] | p[[2]] | p[[3]]

```



## Test cell cycle regression
```{r}
pdx_lungs_cc <- pdx_lungs %>%
  ScaleData(
    vars.to.regress = c("S.Score", "G2M.Score"),
    features = rownames(x = pdx_lungs)) %>%
  RunPCA() %>%
  FindNeighbors(reduction = "pca", k.param = 100L) %>%
  FindClusters(resolution = 0.8) %>%
  RunUMAP(reduction = "pca", dims = 1:30)

r_dim_plot(pdx_lungs_cc, group.by = "Phase")

pdx_lungs_cc <- run_fdl(pdx_lungs_cc)

r_dim_plot(pdx_lungs_cc, group.by = "seurat_clusters", reduction = "fdl")
r_feature_plot(pdx_lungs_cc, "PAX7", reduction = "fdl")
```






